# -----------------------------------------------------------------------------
# Site settings
# -----------------------------------------------------------------------------
name: Kai Wu
email: kaywu@ece.ubc.ca
description: > # this means to ignore newlines until "url:"
  A simple, whitespace theme for academics. Based on [*folio](https://github.com/bogoli/-folio) design.
footer_text: >
  Powered by <a href="http://jekyllrb.com/" target="_blank">Jekyll</a> with <a href="https://github.com/alshedivat/al-folio">al-folio</a> theme.
  Hosted by <a href="https://pages.github.com/" target="_blank">GitHub Pages</a>.

url: "//imkaywu.github.io" # the base hostname & protocol for your site
baseurl: # the subpath of your site, e.g. /blog/
last_updated: # leave blank if you don't want to display last updated

# -----------------------------------------------------------------------------
# Social integration
# -----------------------------------------------------------------------------
github_username: imkaywu # put your github username
twitter_username: _BlacKay_ # put your twitter username
linkedin_username: kai-wu-aa84a779/ # put your linkedin username
scholar_authorid: # put your google scholar author id
contact_note: >
  You can even add a little note about which of these is the best way to reach you.

# -----------------------------------------------------------------------------
# Blog
# -----------------------------------------------------------------------------
blog_name: Kai's blog
blog_description: "A student pursuing computer vision who also likes music, movies, and coding"

# Pagination
paginate: 10
permalink: /blog/:year/:month/:title/
paginate_path: /blog/page:num/
timezone: Canada/Pacific # http://en.wikipedia.org/wiki/List_of_tz_database_time_zones

text:
  pagination:
    newer: 'Newer'
    older: 'Older'

# Comments
disqus_shortname: kaystechblog # put your disqus shortname

# Optional features
show_social_icons:  false
enable_anchorjs:    false
mathjax: true

# -----------------------------------------------------------------------------
# Collections
# -----------------------------------------------------------------------------
collections:
  news:
    defaults:
      layout: post
    output: true
    permalink: /news/:path/
  projects:
    output: true
    permalink: /projects/:path/

news_limit: 5 # ?

# -----------------------------------------------------------------------------
# Defaults
# -----------------------------------------------------------------------------
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: "post"
  # _projects
  - scope:
      path: ""
      type: projects
    values:
      layout: "page"

# -----------------------------------------------------------------------------
# Jekyll settings
# -----------------------------------------------------------------------------

# Build settings
markdown: kramdown
highlighter: rouge

# Markdown Processing
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Reading Files
include:
  - .htaccess
  - _pages
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - Rakefile
  - README
  - tmp
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Gems
gems:
    - jekyll-paginate
    - jemoji

# -----------------------------------------------------------------------------
# Other settings
# -----------------------------------------------------------------------------
jquery_version: "1.12.4"
# katex_version: "0.7.1"
anchorjs_version: "3.2.2"
